#!/usr/bin/env bash

## This will install a Bamboo compatible Java JDK on a Rapsberry Pi 3
##
## Why ?
## A fairly common error with remote agents:
##   https://confluence.atlassian.com/bamkb/a-remote-agent-is-loading-on-bamboo-ui-never-finishes-744326117.html
## caused by an incompatible version of JDK on the remote agent server. (in this case the rpi).
##   https://confluence.atlassian.com/bamboo/supported-platforms-289276764.html
##
## Proposed solution (Robert Watson , Atlassian)
##     For my environments I use the official Oracle JDK, with the following script:
##       sudo apt-get update
##       sudo add-apt-repository ppa:webupd8team/java -y
##       sudo apt-get update
##       sudo apt-get install oracle-java8-installer -y
##     manually accept the license agreement
##
##     the following line may change depending on linux distro
##       sudo echo 'JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"' >> /etc/environment
##     You can also use the following to ensure the version of java used by default is the latest (in case there are multiple versions present on the server):
##       sudo update-alternatives --config javac
##       sudo update-alternatives --config java
##
## Problem : adding debian repository on arm is a big no-no
## Proposed solution : http://www.rpiblog.com/2014/03/installing-oracle-jdk-8-on-raspberry-pi.html

clear

echo '      ____              __        '
echo '     / __ \   ____ _   / /      ___ '
echo '    / / / /  / __ `/  / /      / _ \'
echo '   / /_/ /  / /_/ /  / /___   /  __/'
echo '  /_____/   \__,_/  /_____/   \___/ '
echo ''
echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
echo '    |L|i|n|u|x|s|h|e|l|l| |C|L|I|'
echo '    +-+-+-+-+-+-+-+-+-+-+ +-+-+-+'
echo ''
echo '  >> Author : David Lejeune'
echo "  >> Created : 31/08/2017"
echo ''
echo ' ###################################'
echo ' #  INSTALLING COMPATIBLE JDK FOR  #'
echo ' #   BAMBOO REMOTE AGENT ON PI 3   #'
echo ' ###################################'
echo ''

echo ''
echo "Extract jdk-8-linux-arm-vfp-hflt.tar.gz to /opt directory"
sudo tar zxvf jdk-8u144-linux-arm32-vfp-hflt.tar.gz -C /opt

echo ''
echo "Set default java and javac to the new installed jdk8."
sudo update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_144/bin/javac 1
sudo update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_144/bin/java 1
sudo update-alternatives --config javac
sudo update-alternatives --config java

echo ''
echo "Verify java and javac version"
java -version
javac -version
